services:
  php-fpm:
    container_name: php-fpm
    build:
      context: ./
      dockerfile: ./Dockerfile
    networks:
      - news-api
    volumes:
      - ./:/var/www/news-api

  nginx:
    container_name: nginx
    image: nginx:1.23.2-alpine
    networks:
      - news-api
    ports:
      - '80:80'
    depends_on:
      - php-fpm
    volumes:
      - ./:/var/www/news-api
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

###> doctrine/doctrine-bundle ###
  database:
    container_name: database
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    networks:
      - news-api
    ports:
      - '5432:5432'
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    healthcheck:
      test: ["CMD", "pg_isready -U ${POSTGRES_USER}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

networks:
  news-api:
    driver: bridge

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
